server:
  port: 8083

msa:
  client:
    url:
      gateway: http://localhost:8080 # gateway 주소

spring:
  r2dbc:
    url: r2dbc:h2:mem:///lecture;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    initialization-mode: always
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
debug: false

jwt:
  #BASE64 인코딩 : codestates-bithumb-msa-team-member-spring-boot-webflux-jwt-secret
  secret: Y29kZXN0YXRlcy1iaXRodW1iLW1zYS10ZWFtLW1lbWJlci1zcHJpbmctYm9vdC13ZWJmbHV4LWp3dC1zZWNyZXQ=
  accessExpires:  7200000 #2시간 ms
  refreshExpires:  172800000 #2주 ms


